runtime: nodejs16 # Update this to the latest supported Node.js version
instance_class: F2 # The F2 instance class offers a balance of performance and cost. Adjust as needed.

automatic_scaling:
  target_cpu_utilization: 0.65 # Scale instances based on CPU usage
  min_instances: 1 # Minimum number of instances
  max_instances: 10 # Maximum number of instances
  target_throughput_utilization: 0.6 # Increase the number of instances if the load increases
  max_concurrent_requests: 50 # Maximum number of concurrent requests per instance

env_variables:
  NODE_ENV: 'production'

entrypoint: npm run start # Update this to your app's start command

network: # Networking settings
  instance_tag: nextjs-app # Networking tag
  forwarded_ports:
    - 8080/tcp

liveness_check: # Health checking settings
  path: "/_next/static/" # You might want to change this to a more specific health check route
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check: # Health checking settings
  path: "/_next/static/" # You might want to change this to a more specific health check route
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

