import './globals.css'
import Navbar from './Navbar';
import { Archivo } from 'next/font/google'


const archivo = Archivo({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
